In [10]:
# It's very common to alias numpy as np.
import numpy as np

In [16]:
# Creating a numpy array out of Python lists or other iterables
a = np.array([1, 2, 3, 4, 5]) # Make a numpy array out of a list
a

array([1, 2, 3, 4, 5])

In [2]:

a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a > 3

array([False, False, False,  True,  True,  True])

In [4]:
a[a > 3]

array([4, 5, 6])

In [5]:
greater_than_three = a > 3

In [6]:
a[greater_than_three]

array([4, 5, 6])

In [7]:
a

array([1, 2, 3, 4, 5, 6])

In [8]:
# If we need to (re)assign the variable, then we do so.. Masking returns a copy
b = a[greater_than_three]
b

array([4, 5, 6])

In [9]:
a

array([1, 2, 3, 4, 5, 6])