In [2]:
import numpy as np

In [3]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a > 3

array([False, False, False,  True,  True,  True])

In [5]:
a[a > 3]

array([4, 5, 6])

In [6]:
greater_than_three = a > 3

In [7]:
a[greater_than_three]

array([4, 5, 6])

In [8]:
a

array([1, 2, 3, 4, 5, 6])

In [9]:
# If we need to (re)assign the variable, then we do so.. Masking returns a copy
b = a[greater_than_three]
b

array([4, 5, 6])

In [10]:
a

array([1, 2, 3, 4, 5, 6])