In [1]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [5]:
# If you have an array of booleans, you have the keys to the castle
a < 0

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [6]:
# How many negative numbers are there?
mask = a < 0
mask

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [8]:
# array[boolean_mask]
only_negative_numbers = a[mask]
only_negative_numbers

array([-2, -1, -6, -7])

In [10]:
only_negative_numbers.size

4

In [15]:
less_than_zero = a < 0
less_than_zero.sum()

4

In [11]:
# (array < 0).sum()
# .sum is counting the True values
(a < 0).sum()

4

In [17]:
# What's the proportion of negative values to all values in this array
(a < 0).mean()

0.3333333333333333

In [19]:
(a < 0).sum() / a.size

0.3333333333333333

In [18]:
a.size

12

In [20]:
# built-in sum with a list of booleans works out here
sum([True, False, True])

2

In [21]:
# How many negative numbers are there?
# One liner:
# Think of this as SELECT a from a where a < 0
a[a < 0].size

4

In [22]:
# How many positive numbers are there?
# One liner: a[a > 0].size

is_positive = a > 0
only_positive_numbers = a[is_positive]
only_positive_numbers.size

5

In [24]:
# You're going to see this A LOT!
# .sum on a list of boolean is counting the True values
# .mean on a list of booleans tells you the % True of that list of booleans
(a > 0).sum()

5

In [27]:
# How many even positive numbers are there?
# & is the AND operator for numpy arrays

is_positive = a > 0
is_even = a % 2 == 0 

# True and True is the only & that produces True
mask = is_positive & is_even
print(mask)
a[mask]

[ True  True  True False False False False False False False False False]


array([ 4, 10, 12])

In [33]:
# One liner for many even positive numbers are there?
# Parenetheses are required if the boolean expressions aren't in a variable
a[(a > 0) & (a % 2 == 0)].size

3

In [32]:
((a > 0) & (a % 2 == 0)).sum()

3

In [34]:
# If you were to add 3 to each data point, how many positive numbers would there be?
plus_three = a + 3
(plus_three > 0).sum() # sum is summing the True values of the boolean array

10

In [35]:
plus_three[plus_three > 0].size

10

In [36]:
# If you squared each number, what would the new mean and standard deviation be?
(a**2).mean()

74.0

In [37]:
(a ** 2).std()

144.0243035046516

In [39]:
# A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.
# Centering is also known as de-meaning a vector
avg = a.mean()
avg

3.0

In [40]:
a - avg

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [42]:
(a - a.mean()).mean()

0.0

In [45]:
# Calculate the z-score for each data point.
# Recall that the z-score is given by (x - avg(x)) / std(x)
# zscore is a measure of how many standard deviations away from the mean a value is
numerator = (a - a.mean())
numerator

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [48]:
a.mean()

3.0

In [46]:
denominator = a.std()
denominator

8.06225774829855

In [47]:
numerator / denominator

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [50]:
from scipy import stats

In [51]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [52]:
# What is the difference between np.mean(a) and a.mean?
# Super short answer: the same

In [53]:
np.mean(a)

3.0

In [54]:
a.mean()

3.0

In [55]:
# A function that lives on an object is called a method
# What is our object?
# What is our method?
a.mean() 

3.0

In [57]:
# import numpy as np
# Mean is a function defined on the np module
# We need to provide the values to get the mean from in the parenthes
np.mean(a)

3.0

In [58]:
# Some functions are only defined on np
# Example:
np.array([1, 2, 3])

array([1, 2, 3])

In [60]:
a.std()

8.06225774829855

In [61]:
np.std(a)

8.06225774829855